version: "3.2"

services:

  php_sf:
    container_name: php_sf
    build:
      context: './php/'
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/sf

  mysql_sf:
    container_name: mysql_sf
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_PASSWORD: pwd

  nginx_sf:
    container_name: nginx_sf
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_sf
      - mysql_sf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_sf
      PMA_USER:  root
      PMA_PASSWORD: pwd
    ports:
      - "8080:80"